basePath: /
consumes:
- application/json
info:
  contact:
    email: support@e154.ru
    name: Alex Filippov
    url: https://e154.github.io/smart-home-gate/
  description: This documentation describes APIs found under https://github.com/e154/smart-home-gate
  license:
    name: MIT
    url: https://raw.githubusercontent.com/e154/smart-home-gate/master/LICENSE
  title: Smart home gate
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - text/plain
      operationId: index
      produces:
      - text/plain
      responses:
        "200":
          description: Success response
      summary: index page
      tags:
      - index
  /check/mobile_access:
    get:
      consumes:
      - text/plain
      operationId: check
      produces:
      - text/plain
      responses:
        "200":
          description: Success response
      summary: mobile access connection page
      tags:
      - check
  /check/mobile_access_token:
    get:
      consumes:
      - text/plain
      operationId: check
      produces:
      - text/plain
      responses:
        "200":
          description: Success response
        "400":
          description: Bad request
        "404":
          description: Not found
      security:
      - ServerAuthorization: []
      summary: mobile access token check page
      tags:
      - check
  /server/{any}:
    get:
      consumes:
      - text/plain
      operationId: server
      produces:
      - text/plain
      responses:
        "200":
          description: Success response
        "400": {}
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500": {}
      security:
      - ServerAuthorization: []
      summary: proxy controllers to server
      tags:
      - server
produces:
- application/json
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  ServerAuthorization:
    in: header
    name: ServerAuthorization
    type: apiKey
swagger: "2.0"
